# Generated by Django 2.2.16 on 2021-01-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='leng',
            field=models.PositiveSmallIntegerField(choices=[(3, 'ua'), (1, 'ru'), (2, 'en')]),
        ),
    ]
