# Generated by Django 2.2.16 on 2021-01-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210115_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='leng',
            field=models.PositiveSmallIntegerField(choices=[(2, 'en'), (3, 'uk'), (1, 'ru')]),
        ),
    ]
