# Generated by Django 2.2.16 on 2021-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210115_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='leng',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ru'), (3, 'uk'), (2, 'en')]),
        ),
    ]
