# Generated by Django 2.2.16 on 2021-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210115_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='leng',
            field=models.PositiveSmallIntegerField(choices=[(2, 'en'), (1, 'ru'), (3, 'uk')]),
        ),
    ]
