# Generated by Django 2.2.16 on 2021-01-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210115_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='leng',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ru'), (2, 'en'), (3, 'uk')]),
        ),
    ]
